server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true