server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB